/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solutions.mundovirtual.common;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("Name:Computer Description:Device for programing Price:1200.0", classUnderTest.getGreeting());
    }
}
