/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solutions.mundovirtual.common;

import solutions.mundovirtual.common.model.Product;

public class App {
    public String getGreeting() {
        Product product = new Product("Computer", "Device for programing", 1200.0);
        return product.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
